### ISSUE TITLE
BFO Tool does not fail gracefully

### ISSUE THREAD

**Issue by cogan-shimizu-wsu** [comodide/CoModIDE#37]
When failing to load a new ontology it should indicate the error message by catching the error, writing to the log, and then allowing for a new ontology to be loaded.

For testing purposes, I suggest the use of the enslavedontologyv2.owl which can be found online (enslaved.org).

**Comment by abhiarydalal11** [comment]
Checked it with enslaved ontology file and it is working.
We can check with different files to see if this fails or not.

**Comment by cogan-shimizu-wsu** [comment]
Can you try opening a few of the different ontology design patterns (say from the modl section of resources)?

**Comment by abhiarydalal11** [comment]
these files(from the modl section) are failing with error dialog box:-
provenance.owl
quantities.owl
temporalextent.owl
Fix :- https://github.com/comodide/CoModIDE/commit/fa3c82b1a1f6b9ae1e7fa84080aab026d1d96456
