### ISSUE TITLE
Upper Alignment Tool creates wrong entity names

### ISSUE THREAD

**Issue by cogan-shimizu-wsu** [comodide/CoModIDE#38]
When adding a superclass from the upper alignment tool, the tool creates an entity with the type  `concept name (label)` when it should only be `concept name`. I suspect this is an issue with the concept creation. It's ok if the concept has the same namespace as the target ontology, but it should share the concept name from the aligned upper ontology.

**Comment by abhiarydalal11** [comment]
Fixed it, Now it will be having rdf labels in case owl file have them and if the owl file doesn't have rdf labels it will have the entity short name.

**Comment by abhiarydalal11** [comment]
Fix:- https://github.com/comodide/CoModIDE/commit/6859506f335c92db207800c1e13b4b8581074c5b#diff-1604fa5d6da75d1ecf82b090e246f2db
