### ISSUE TITLE
Upper Alignment Tool should allow to reload ontologies

### ISSUE THREAD

**Issue by cogan-shimizu-wsu** [comodide/CoModIDE#39]
While not strictly necessary, it would be nice to have a button to bring back the "load ontology" view of the upper alignment tool. It would make testing easy and also not necessary to reopen the view (or restart comodide) to change which ontology needs to be loaded. (This would be useful if you're just borrowing from a number of different vocabularies).

**Comment by abhiarydalal11** [comment]
Fix :- https://github.com/comodide/CoModIDE/commit/6859506f335c92db207800c1e13b4b8581074c5b#diff-1604fa5d6da75d1ecf82b090e246f2db
