### ISSUE TITLE
comodide gets load with an exception 

### ISSUE THREAD

**Issue by abhiarydalal11** [comodide/CoModIDE#49]
comodide gets load with an [IllegalArgumentException] - "the number of splits must correspond to the number of children"

<img width="500" alt="new" src="https://user-images.githubusercontent.com/56659194/95381013-2c44c180-08ad-11eb-81f5-eaed18b2833e.PNG">

**Comment by abhiarydalal11** [comment]
[protege (1).log](https://github.com/comodide/CoModIDE/files/5343461/protege.1.log)
 Log File is attached.

**Comment by hammar** [comment]
If you reset the tab (Window/Reset selected tab to default state), does this go away? If not we have an inconsistency in the viewConfig file that needs to be resolved. Which branch is this?

**Comment by abhiarydalal11** [comment]
One of the users was facing the issue, and it got fixed with the new jar file CoModIDE 1.1.1.jar.
