### ISSUE TITLE
Edge Inspector View shows cellID instead of Label

### ISSUE THREAD

**Issue by cogan-shimizu** [comodide/CoModIDE#79]
When clicking on an edge and using the edge inspector view it displays a number before the list of axioms, this should be the label for the edge instead.

**Comment by Ambar-Shrivastava** [comment]
To make this change, below line change has been done in class EdgeInspectorView. java
From: this.edgeLabel.setText(this.currentSelectedCell.getId());
To: this.edgeLabel.setText((String) this.currentSelectedCell.getValue());

**Comment by cogan-shimizu** [comment]
Related request with additional info #89
